on:
  push:
    tags:
    - '*'
    
name: Zip up folders for distribution

jobs:
  build:
    name: Zip up folders for distribution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Zip files
        run: |
          zip -r bjorn.zip bjorn/
          zip -r video.zip video/
          zip -r frances.zip frances/
          zip -r william.zip william/
          zip -r interviews.zip interviews/
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false
          
      - name: upload Bjorn
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}  
          asset_path: ./bjorn.zip
          asset_name: bjorn.zip
          asset_content_type: application/zip

      - name: upload Frances
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}  
          asset_path: ./frances.zip
          asset_name: frances.zip
          asset_content_type: application/zip
